import "./globals.css";
import { Orbit } from "next/font/google";

const inter = Orbit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "I love WOW hardcore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
